### ISSUE TITLE
Celestia-app ADR006: `WriteNamespacedPaddedShares`

### ISSUE THREAD

**Issue by sergio-mena** [informalsystems/audit-celestia#20]
I'm not sure I understand the manipulation of indices of the code snippet describing `WriteNamespacedPaddedShares` in ADR006.
The array is 2-dimensional (slice of slices), but its usage later seems 1-dimensional.

After a synchronous discussion, it's clear it is not matching the actual code, so, very likely, this is just a documentation issue and not an actual bug.

**Comment by rootulp** [comment]
The line of interest in the ADR is [here](https://github.com/celestiaorg/celestia-app/blob/082083f797d606dd7694e12b03f2bd5edf34d02c/docs/architecture/adr-006-non-interactive-defaults.md?plain=1#L130). Since the ADR was published, we removed the type `NamespacedShare` and renamed `MessageShareSplitter` => `SparseShareSplitter`. The relevant lines in the implementation are now 
1. https://github.com/celestiaorg/celestia-app/blob/082083f797d606dd7694e12b03f2bd5edf34d02c/pkg/shares/split_sparse_shares.go#L16
2. https://github.com/celestiaorg/celestia-app/blob/082083f797d606dd7694e12b03f2bd5edf34d02c/pkg/shares/split_sparse_shares.go#L70

Since the implementation now uses a 1-dimensional slice, it looks like there is no longer a code bug but agreed the documentation is confusing.

**Comment by sergio-mena** [comment]
I see.
Then I guess the easiest fix is just to adapt the ADR to define `shares` as a 1-dimensional array. This is just a suggestion.

**Comment by sergio-mena** [comment]
After looking at the actual code, I understand `count` always matches the array length. If my understanding is right, consider getting rid of `count` and using `len(sss.shares)` instead. [minor simplification]
