### ISSUE TITLE
Too many namespace prefixes per share?

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#5]
In [CreateCommitment](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/payfordata.go#L125), the commit is the hash of the roots of a set of NMT subtrees. The leafs of an NMT subtree are added by calling the [Push](https://github.com/celestiaorg/celestia-core/blob/60930abb43458e1f8b321d1eb9e5d6b174975e35/pkg/wrapper/nmt_wrapper.go#L50) method of `ErasuredNamespacedMerkleTree` (see [here](https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/payfordata.go#L163)), i.e., 
```golang
// leaf is of type []byte and consist of nid | datalen | data
nsLeaf := append(make([]byte, 0), append(namespace, leaf...)...)
// => nsLeaf = namespace | nid | datalen | data
tree.Push(nsLeaf, rsmt2d.SquareIndex{Axis: 0, Cell: 0})
```
`ErasuredNamespacedMerkleTree.Push()` prefixes the data once again with the namespace before pushing it to the underlying NMT tree (see [here](https://github.com/celestiaorg/celestia-core/blob/60930abb43458e1f8b321d1eb9e5d6b174975e35/pkg/wrapper/nmt_wrapper.go#L54)), i.e., 
```golang
func (w *ErasuredNamespacedMerkleTree) Push(data []byte, idx rsmt2d.SquareIndex) {
  // ...  
  nidAndData := make([]byte, consts.NamespaceSize+len(data))
  copy(nidAndData[consts.NamespaceSize:], data)
  copy(nidAndData[:consts.NamespaceSize], data[:consts.NamespaceSize])
  // => nidAndData = namespace | namespace | nid | datalen | data
  // push to the underlying tree
  err := w.tree.Push(nidAndData)
}
```
Is this behavior intentional? It seems that they are too many namespace IDs for every share.

**Comment by evan-forbes** [comment]
> Is this behavior intentional? It seems that they are too many namespace IDs for every share.

great question, we need to elaborate more on this in our docs. As briefly mentioned [here](https://github.com/celestiaorg/celestia-core/blob/60930abb43458e1f8b321d1eb9e5d6b174975e35/pkg/wrapper/nmt_wrapper.go#L20-L22), the namespaces have to be included in the erasure data. This means that nmt cannot rely on the first `consts.NamesapceSize` bytes to provide it with the namespace, because it when it pushes erasure data, instead of using the correct namespace (the parity namespace) it will use the first 8 bytes of the erasure data. This is why we add the namespace again when pushing a leaf using this wrapper, is so that nmt can still be an independent useful library, while also adding the correct namespace to each leaf.

**Comment by rootulp** [comment]
Is there anything remaining on this issue?

> Is this behavior intentional?

Based on response above, it seems yes.
