### ISSUE TITLE
`ShareCommitAndSignature.K` should be bounded

### ISSUE THREAD

**Issue by mpoke** [informalsystems/audit-celestia#9]
In `MsgWirePayForData.ValidateBasic()`,  `ShareCommitAndSignature.K` is only required to be a power of two, see https://github.com/celestiaorg/celestia-app/blob/9e01bd307d428fffcd1a8a66e0d97719a3e83d90/x/payment/types/wirepayfordata.go#L107. As a result, a malicious user can spam the system by sending `MsgWirePayForData` transactions with
- `k > MaxSquareSize`
- `k < MinSquareSize`
- multiple `ShareCommitAndSignature`s for the same `k`.

**Comment by rootulp** [comment]
With the introduction of [`ValidateAllSquareSizesCommitedTo`](https://github.com/celestiaorg/celestia-app/blob/7ca6eca76824fc54816243da9a695f56669cc27f/x/payment/types/wirepayfordata.go#L142-L156) it looks like:
- `k > MaxSquareSize` will fail this check
- `k < MinSquareSize` will fail this check
- multiple `ShareCommitAndSignatures` for the same `k` will fail this check because each square size is expected to be signed once [here](https://github.com/celestiaorg/celestia-app/blob/7ca6eca76824fc54816243da9a695f56669cc27f/x/payment/types/wirepayfordata.go#L171-L179)

Are there any other unaccounted for scenarios where `ShareCommitAndSignature.K` should be bounded?

**Comment by mpoke** [comment]
@rootulp LGTM. [ValidateAllSquareSizesCommitedTo](https://github.com/celestiaorg/celestia-app/blob/7ca6eca76824fc54816243da9a695f56669cc27f/x/payment/types/wirepayfordata.go#L142-L156) fixes the issue.
